<?xml version="1.0" encoding="utf-8"?><Database Name="VWCMS" Class="webdataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SERVER2003;Initial Catalog=VWCMS;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VWCMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.t_ColumnUpdate" Member="t_ColumnUpdate">
    <Type Name="t_ColumnUpdate">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColumnID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Company" Member="t_Company">
    <Type Name="t_Company">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ListPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Group" Member="t_Group">
    <Type Name="t_Group">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="ParentUID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Log" Member="t_Log">
    <Type Name="t_Log">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Action" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descrition" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Param" Member="t_Param">
    <Type Name="t_Param">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Options" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_ParamValue" Member="t_ParamValue">
    <Type Name="t_ParamValue">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Priority" Member="t_Priority">
    <Type Name="t_Priority">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Product" Member="t_Product">
    <Type Name="t_Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SN" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_ProductMode" Member="t_ProductMode">
    <Type Name="t_ProductMode">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SeriesID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_ProductSeries" Member="t_ProductSeries">
    <Type Name="t_ProductSeries">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="EnglishName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Property" Member="t_Property">
    <Type Name="t_Property">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ObjectType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.t_Resource" Member="t_Resource">
    <Type Name="t_Resource">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="SubTitle" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TextType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="ParentUID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="GroupUID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Text" Member="t_Text">
    <Type Name="t_Text">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.t_UpdateItem" Member="t_UpdateItem">
    <Type Name="t_UpdateItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UpdateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="ListPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.t_User" Member="t_User">
    <Type Name="t_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.t_Column" Member="t_Column">
    <Type Name="t_Column">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Brief" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="ParentUID" Type="System.String" DbType="NVarChar(36)" CanBeNull="true" />
      <Column Name="Template" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SEO_Keyword" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SEO_Title" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SEO_Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>